# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestZimra():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_zimra(self):
    # Test name: Zimra
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://mail.nitrkl.ac.in/")
    # 2 | setWindowSize | 2064x1127 | 
    self.driver.set_window_size(2064, 1127)
    # 3 | click | id=zlif__CLV-main__-2158__rw | 
    self.driver.find_element(By.ID, "zlif__CLV-main__-2158__rw").click()
    # 4 | click | css=#zlif__CLV-main__-2157__su > span:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, "#zlif__CLV-main__-2157__su > span:nth-child(1)").click()
    # 5 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 6 | click | id=zlif__CLV-main__-2147__r3 | 
    self.driver.find_element(By.ID, "zlif__CLV-main__-2147__r3").click()
    # 7 | click | id=zlif__CLV-main__-2148__r3 | 
    self.driver.find_element(By.ID, "zlif__CLV-main__-2148__r3").click()
    # 8 | click | id=zti__main_Mail__5_textCell | 
    self.driver.find_element(By.ID, "zti__main_Mail__5_textCell").click()
    # 9 | click | id=zti__main_Mail__6_textCell | 
    self.driver.find_element(By.ID, "zti__main_Mail__6_textCell").click()
    # 10 | click | id=zti__main_Mail__4_textCell | 
    self.driver.find_element(By.ID, "zti__main_Mail__4_textCell").click()
    # 11 | click | id=zti__main_Mail__3_textCell | 
    self.driver.find_element(By.ID, "zti__main_Mail__3_textCell").click()
    # 12 | click | id=zb__App__Contacts_title | 
    self.driver.find_element(By.ID, "zb__App__Contacts_title").click()
    # 13 | click | id=zb__App__Calendar_title | 
    self.driver.find_element(By.ID, "zb__App__Calendar_title").click()
    # 14 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 15 | click | id=zb__App__Tasks_title | 
    self.driver.find_element(By.ID, "zb__App__Tasks_title").click()
    # 16 | click | id=zb__App__Options_title | 
    self.driver.find_element(By.ID, "zb__App__Options_title").click()
    # 17 | click | id=zb__App__Mail_title | 
    self.driver.find_element(By.ID, "zb__App__Mail_title").click()
    # 18 | click | css=#zti__main_Mail__2_textCell > span | 
    self.driver.find_element(By.CSS_SELECTOR, "#zti__main_Mail__2_textCell > span").click()
    # 19 | click | id=zlif__CLV-main__-2156__r3 | 
    self.driver.find_element(By.ID, "zlif__CLV-main__-2156__r3").click()
    # 20 | click | id=zlif__CLV-main__-2155__rw | 
    self.driver.find_element(By.ID, "zlif__CLV-main__-2155__rw").click()
  
