# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestIITM():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_iITM(self):
    # Test name: IITM
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.iitm.ac.in/")
    # 2 | setWindowSize | 1477x797 | 
    self.driver.set_window_size(1477, 797)
    # 3 | click | css=.container > .navigation__slideShow .navigation__submenudropdown:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".container > .navigation__slideShow .navigation__submenudropdown:nth-child(1)").click()
    # 4 | click | linkText=Computer Science and Engineering | 
    self.driver.find_element(By.LINK_TEXT, "Computer Science and Engineering").click()
    # 5 | click | linkText=Visit the Department of Computer Science & Engineering | 
    self.vars["window_handles"] = self.driver.window_handles
    # 6 | storeWindowHandle | root | 
    self.driver.find_element(By.LINK_TEXT, "Visit the Department of Computer Science & Engineering").click()
    # 7 | selectWindow | handle=${win5493} | 
    self.vars["win5493"] = self.wait_for_window(2000)
    # 8 | click | linkText=UG & PG Curriculum | 
    self.vars["root"] = self.driver.current_window_handle
    # 9 | close |  | 
    self.driver.switch_to.window(self.vars["win5493"])
    # 10 | selectWindow | handle=${root} | 
    self.driver.find_element(By.LINK_TEXT, "UG & PG Curriculum").click()
    # 11 | click | linkText=Intelligent Systems & Human Computer Interaction | 
    self.driver.close()
    # 12 | click | linkText=Intelligent Systems & Human Computer Interaction | 
    self.driver.switch_to.window(self.vars["root"])
    # 13 | click | linkText=About IIT Madras | 
    self.driver.find_element(By.LINK_TEXT, "Intelligent Systems & Human Computer Interaction").click()
    # 14 | click | linkText=Mission | 
    self.driver.find_element(By.LINK_TEXT, "Intelligent Systems & Human Computer Interaction").click()
    self.driver.find_element(By.LINK_TEXT, "About IIT Madras").click()
    self.driver.find_element(By.LINK_TEXT, "Mission").click()
  
