# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestXbox():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_xbox(self):
    # Test name: Xbox
    # Step # | name | target | value
    # 1 | open | /en-IN/ | 
    self.driver.get("https://www.xbox.com/en-IN/")
    # 2 | setWindowSize | 1464x784 | 
    self.driver.set_window_size(1464, 784)
    # 3 | click | css=a:nth-child(3) .c-paragraph | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(3) .c-paragraph").click()
    # 4 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 5 | runScript | window.scrollTo(0,1831.4285888671875) | 
    self.driver.execute_script("window.scrollTo(0,1831.4285888671875)")
    # 6 | runScript | window.scrollTo(0,2997.142822265625) | 
    self.driver.execute_script("window.scrollTo(0,2997.142822265625)")
    # 7 | click | css=.c-call-to-action:nth-child(4) > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".c-call-to-action:nth-child(4) > span").click()
    # 8 | runScript | window.scrollTo(0,4) | 
    self.driver.execute_script("window.scrollTo(0,4)")
    # 9 | click | linkText=FAQ | 
    self.driver.find_element(By.LINK_TEXT, "FAQ").click()
    # 10 | click | linkText=Xbox Support | 
    self.driver.find_element(By.LINK_TEXT, "Xbox Support").click()
    # 11 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 12 | click | id=service-status | 
    self.driver.find_element(By.ID, "service-status").click()
  
