# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestJio():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_jio(self):
    # Test name: Jio
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.jio.com/")
    # 2 | setWindowSize | 1477x797 | 
    self.driver.set_window_size(1477, 797)
    # 3 | mouseOver | linkText=AirFiber | 
    element = self.driver.find_element(By.LINK_TEXT, "AirFiber")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | click | linkText=AirFiber | 
    self.driver.find_element(By.LINK_TEXT, "AirFiber").click()
    # 5 | runScript | window.scrollTo(0,342.28570556640625) | 
    self.driver.execute_script("window.scrollTo(0,342.28570556640625)")
    # 6 | runScript | window.scrollTo(0,600) | 
    self.driver.execute_script("window.scrollTo(0,600)")
    # 7 | click | css=.j-container:nth-child(3) > .j-button > div | 
    self.driver.find_element(By.CSS_SELECTOR, ".j-container:nth-child(3) > .j-button > div").click()
    # 8 | click | css=.group:nth-child(3) .j-link:nth-child(4) .j-text | 
    self.driver.find_element(By.CSS_SELECTOR, ".group:nth-child(3) .j-link:nth-child(4) .j-text").click()
    # 9 | click | id=AoutUsSelect | 
    self.driver.find_element(By.ID, "AoutUsSelect").click()
    # 10 | click | css=.col-sm-6 li:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-sm-6 li:nth-child(2)").click()
    # 11 | click | linkText=Galleria | 
    self.driver.find_element(By.LINK_TEXT, "Galleria").click()
    # 12 | click | linkText=Awards | 
    self.driver.find_element(By.LINK_TEXT, "Awards").click()
  
