# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestWikipedia():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_wikipedia(self):
    # Test name: wikipedia
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.wikipedia.org/")
    # 2 | setWindowSize | 1936x1056 | 
    self.driver.set_window_size(1936, 1056)
    # 3 | type | id=searchInput | software
    self.driver.find_element(By.ID, "searchInput").send_keys("software")
    # 4 | sendKeys | id=searchInput | ${KEY_ENTER}
    self.driver.find_element(By.ID, "searchInput").send_keys(Keys.ENTER)
    # 5 | runScript | window.scrollTo(0,2100) | 
    self.driver.execute_script("window.scrollTo(0,2100)")
    # 6 | click | linkText=Programming tool | 
    self.driver.find_element(By.LINK_TEXT, "Programming tool").click()
    # 7 | mouseOver | linkText=Build automation | 
    element = self.driver.find_element(By.LINK_TEXT, "Build automation")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | mouseOut | linkText=Build automation | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 9 | click | linkText=Binary compatibility | 
    self.driver.find_element(By.LINK_TEXT, "Binary compatibility").click()
    # 10 | click | linkText=Bug compatibility | 
    self.driver.find_element(By.LINK_TEXT, "Bug compatibility").click()
    # 11 | click | linkText=AARD code | 
    self.driver.find_element(By.LINK_TEXT, "AARD code").click()
    # 12 | click | css=#toc-Discovery .vector-toc-text | 
    self.driver.find_element(By.CSS_SELECTOR, "#toc-Discovery .vector-toc-text").click()
    # 13 | runScript | window.scrollTo(0,270) | 
    self.driver.execute_script("window.scrollTo(0,270)")
    # 14 | click | linkText=Plug compatible | 
    self.driver.find_element(By.LINK_TEXT, "Plug compatible").click()
  
