# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHackerrank():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_hackerrank(self):
    # Test name: hackerrank
    # Step # | name | target | value
    # 1 | open | /dashboard | 
    self.driver.get("https://www.hackerrank.com/dashboard")
    # 2 | setWindowSize | 1936x1056 | 
    self.driver.set_window_size(1936, 1056)
    # 3 | click | css=#base-card-1-link .ui-text | 
    self.driver.find_element(By.CSS_SELECTOR, "#base-card-1-link .ui-text").click()
    # 4 | mouseOver | css=.first-challenge > #contest-challenges-problem .challengecard-title | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".first-challenge > #contest-challenges-problem .challengecard-title")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseOut | css=.first-challenge > #contest-challenges-problem .challengecard-title | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 6 | mouseOver | css=.first-challenge .content--list_body | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".first-challenge .content--list_body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 7 | mouseOut | css=.first-challenge .content--list_body | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 8 | click | css=.js-track-click:nth-child(2) .cta-container .ui-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".js-track-click:nth-child(2) .cta-container .ui-btn").click()
    # 9 | mouseOver | css=.code-editor-section | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".code-editor-section")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 10 | mouseOut | css=.code-editor-section | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 11 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 12 | mouseOver | css=.community-header-breadcrumb | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".community-header-breadcrumb")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 13 | mouseOut | css=.community-header-breadcrumb | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 14 | mouseOut | css=.view-line:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 15 | click | css=.community-breadcrumb:nth-child(3) > .breadcrumb-item:nth-child(1) .breadcrumb-item-text | 
    self.driver.find_element(By.CSS_SELECTOR, ".community-breadcrumb:nth-child(3) > .breadcrumb-item:nth-child(1) .breadcrumb-item-text").click()
    # 16 | click | css=.nav-link-item:nth-child(4) span | 
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link-item:nth-child(4) span").click()
    # 17 | click | css=.verifiable-role-card:nth-child(2) .role-title | 
    self.driver.find_element(By.CSS_SELECTOR, ".verifiable-role-card:nth-child(2) .role-title").click()
    # 18 | click | css=.nav-link-item:nth-child(3) span | 
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link-item:nth-child(3) span").click()
    # 19 | mouseOver | css=.community-header-breadcrumb-items | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".community-header-breadcrumb-items")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 20 | mouseOut | css=.community-header-breadcrumb-items | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 21 | click | css=.topic-card:nth-child(5) .topic-name | 
    self.driver.find_element(By.CSS_SELECTOR, ".topic-card:nth-child(5) .topic-name").click()
    # 22 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 23 | click | css=.js-track-click:nth-child(1) .content--list_header-v2 > .cta-container .ui-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".js-track-click:nth-child(1) .content--list_header-v2 > .cta-container .ui-btn").click()
    # 24 | mouseOver | css=.js-track-click:nth-child(1) .content--list_header-v2 > .cta-container .ui-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".js-track-click:nth-child(1) .content--list_header-v2 > .cta-container .ui-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 25 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 26 | click | css=.mtk1:nth-child(4) | 
    self.driver.find_element(By.CSS_SELECTOR, ".mtk1:nth-child(4)").click()
    # 27 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 28 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 29 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 30 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 31 | mouseUp | css=.view-line:nth-child(14) | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".view-line:nth-child(14)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
  
